# ! 本项目私有文件

# CI 项目
name: auto-update

# CI 权限
permissions: write-all

# CI 计划
on:
  # 自动运行: 每天早上 3 点
  schedule:
    - cron: 0 19 * * *
  # 手动运行
  workflow_dispatch:
    inputs:
      COMMIT:
        description: 'Commit Message'
        required: false
        type: string
        default: ''

# CI 环境
env:
  # GITHUB ENV
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  # CI ENV
  CI_COMMIT: ${{inputs.COMMIT || ''}} # 为自动编译设置默认值

# CI 任务
jobs:
  auto-update:
    name: auto-update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          token: ${{secrets.WORKFLOW_TOKEN}}

      - name: InitWorkflow
        run: |
          workflowPath="$RUNNER_TEMP/Workflow-$(uuidgen | tr -d '-')"
          git clone --depth=1 https://github.com/zero-dream/action-workflow.git "$workflowPath/" || exit 1
          chmod +x "$workflowPath/zerodream/init/init.sh"
          source "$workflowPath/zerodream/init/init.sh"
          rm -rf "$workflowPath/"
          # --------------------------------------------------
          source "$ZD_ScriptLibPath/hook.sh"
          hook 'AutoUpdate/InitWorkflow'

      - name: UpdateRepo
        run: |
          source "$ZD_ScriptLibPath/createPath.sh"
          source "$ZD_ScriptLibPath/updateRepo.sh"
          updatePath=$(cloneRepo)
          firmwareRepoPath="$(createTempPath 'Temp_FirmwareRepo:dir')"
          git clone --depth=1 https://github.com/zero-dream/zerowrt-firmware.git "$firmwareRepoPath/"
          coverArr=(
            'auto-update'
            'clean-release'
          )
          for cover in "${coverArr[@]}"; do
            cp -a "$updatePath/.github/workflows/$cover.yml" "$firmwareRepoPath/.github/workflows/"
          done
          find "$updatePath/.github/workflows/" -mindepth 1 -delete
          cp -a "$firmwareRepoPath/.github/workflows/." "$updatePath/.github/workflows/"
          rm -rf "$firmwareRepoPath/"
          pushRepo "$CI_COMMIT"
